#!/usr/bin/env python3
"""Render the locked shipped-Wasm dependency inventory and deterministic CycloneDX SBOM."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
TARGET = "wasm32-unknown-unknown"
BEGIN = "<!-- BEGIN LOCKED WASM DEPENDENCIES -->"
END = "<!-- END LOCKED WASM DEPENDENCIES -->"
REGISTRY = "registry+https://github.com/rust-lang/crates.io-index"


def cargo_metadata() -> dict:
    command = [
        "cargo",
        "metadata",
        "--locked",
        "--format-version",
        "1",
        "--filter-platform",
        TARGET,
        "--manifest-path",
        str(ROOT / "Cargo.toml"),
    ]
    return json.loads(subprocess.check_output(command, cwd=ROOT, text=True))


def lock_checksums() -> dict[tuple[str, str, str | None], str | None]:
    lock = tomllib.loads((ROOT / "Cargo.lock").read_text(encoding="utf-8"))
    return {
        (package["name"], package["version"], package.get("source")): package.get("checksum")
        for package in lock["package"]
    }


def closure(metadata: dict) -> tuple[list[dict], dict[str, list[str]], str]:
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    root_id = metadata["resolve"]["root"]
    if root_id is None:
        raise RuntimeError("Cargo metadata did not identify the root package")

    seen: set[str] = set()
    edges: dict[str, list[str]] = {}
    pending = [root_id]
    while pending:
        package_id = pending.pop()
        if package_id in seen:
            continue
        seen.add(package_id)
        selected: list[str] = []
        for dependency in nodes[package_id]["deps"]:
            if any(
                kind["kind"] in (None, "normal", "build")
                for kind in dependency["dep_kinds"]
            ):
                selected.append(dependency["pkg"])
                pending.append(dependency["pkg"])
        edges[package_id] = sorted(set(selected))

    checksums = lock_checksums()
    inventory: list[dict] = []
    for package_id in seen:
        if package_id == root_id:
            continue
        package = packages[package_id]
        source = package["source"]
        if source != REGISTRY:
            raise RuntimeError(
                f"shipped dependency {package['name']} {package['version']} is not from crates.io: {source}"
            )
        if package["name"].startswith("dekopon-") and package["version"] != "0.11.1":
            raise RuntimeError(
                f"Dekopon dependency {package['name']} resolved to {package['version']}, not 0.11.1"
            )
        checksum = checksums.get((package["name"], package["version"], source))
        if not checksum:
            raise RuntimeError(
                f"locked registry checksum is missing for {package['name']} {package['version']}"
            )
        inventory.append(
            {
                "id": package_id,
                "name": package["name"],
                "version": package["version"],
                "license": package.get("license") or "NOASSERTION",
                "source": source,
                "checksum": checksum,
            }
        )
    inventory.sort(key=lambda item: (item["name"], item["version"], item["checksum"]))
    return inventory, edges, root_id


def verify_against_cargo_tree(metadata: dict, inventory: list[dict], root_id: str) -> None:
    command = [
        "cargo",
        "tree",
        "--locked",
        "--target",
        TARGET,
        "--edges",
        "normal,build",
        "--prefix",
        "none",
        "--format",
        "{p}",
        "--manifest-path",
        str(ROOT / "Cargo.toml"),
    ]
    rendered = subprocess.check_output(command, cwd=ROOT, text=True)
    packages: set[tuple[str, str]] = set()
    for line in rendered.splitlines():
        match = re.match(r"^(\S+) v(\S+)(?:\s|$)", line)
        if not match:
            raise RuntimeError(f"could not parse locked Cargo tree line: {line!r}")
        packages.add((match.group(1), match.group(2)))
    by_id = {package["id"]: package for package in metadata["packages"]}
    root = by_id[root_id]
    packages.discard((root["name"], root["version"]))
    expected = {(item["name"], item["version"]) for item in inventory}
    if packages != expected:
        raise RuntimeError(
            "locked metadata traversal differs from cargo tree: "
            f"metadata-only={sorted(expected - packages)}, tree-only={sorted(packages - expected)}"
        )


def text_inventory(inventory: list[dict]) -> str:
    lines = [
        "# Generated by scripts/dependency_inventory.py; do not edit.",
        f"# Locked {TARGET} normal/build closure (root package excluded).",
    ]
    for package in inventory:
        lines.append(
            f"{package['name']}\t{package['version']}\t{package['license']}\tsha256:{package['checksum']}"
        )
    return "\n".join(lines) + "\n"


def notices_block(inventory: list[dict]) -> str:
    lines = [
        BEGIN,
        "## Locked shipped-Wasm dependency inventory",
        "",
        f"The `{TARGET}` normal/build closure contains {len(inventory)} crates (the provider root is excluded).",
        "Versions, license expressions, and registry checksums are generated from `Cargo.lock` and locked Cargo metadata.",
        "",
        "| Crate | Version | Declared license | Locked registry SHA-256 |",
        "|---|---:|---|---|",
    ]
    for package in inventory:
        lines.append(
            f"| `{package['name']}` | `{package['version']}` | `{package['license']}` | `{package['checksum']}` |"
        )
    lines.extend(
        [
            "",
            "The corresponding source archives and full license files are available from crates.io.",
            "`cargo deny` independently checks that every expression is allowed by `deny.toml`.",
            END,
        ]
    )
    return "\n".join(lines)


def replace_notices(existing: str, block: str) -> str:
    if existing.count(BEGIN) != 1 or existing.count(END) != 1:
        raise RuntimeError("THIRD_PARTY_NOTICES.md must contain exactly one generated marker pair")
    prefix, remainder = existing.split(BEGIN, 1)
    _, suffix = remainder.split(END, 1)
    return prefix + block + suffix


def public_item(item: dict) -> dict:
    return {key: value for key, value in item.items() if key != "id"}


def json_inventory(inventory: list[dict]) -> str:
    document = {
        "schemaVersion": 1,
        "target": TARGET,
        "dependencyKinds": ["normal", "build"],
        "rootExcluded": True,
        "dependencies": [public_item(item) for item in inventory],
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def bom_ref(name: str, version: str) -> str:
    return f"pkg:cargo/{quote(name, safe='')}@{quote(version, safe='')}"


def cyclonedx(metadata: dict, inventory: list[dict], edges: dict[str, list[str]], root_id: str) -> str:
    packages = {package["id"]: package for package in metadata["packages"]}
    included = {item["id"] for item in inventory}
    root = packages[root_id]
    root_ref = bom_ref(root["name"], root["version"])
    components = []
    refs: dict[str, str] = {root_id: root_ref}
    for item in inventory:
        reference = bom_ref(item["name"], item["version"])
        refs[item["id"]] = reference
        component = {
            "type": "library",
            "bom-ref": reference,
            "name": item["name"],
            "version": item["version"],
            "purl": reference,
            "hashes": [{"alg": "SHA-256", "content": item["checksum"]}],
            "licenses": [{"expression": item["license"]}],
            "properties": [
                {"name": "dekopon:closure", "value": "normal,build"},
                {"name": "dekopon:target", "value": TARGET},
            ],
        }
        components.append(component)

    dependencies = []
    for package_id in [root_id] + [item["id"] for item in inventory]:
        dependencies.append(
            {
                "ref": refs[package_id],
                "dependsOn": sorted(
                    refs[dependency]
                    for dependency in edges.get(package_id, [])
                    if dependency == root_id or dependency in included
                ),
            }
        )
    dependencies.sort(key=lambda item: item["ref"])
    document = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": {
                "type": "library",
                "bom-ref": root_ref,
                "name": root["name"],
                "version": root["version"],
                "purl": root_ref,
            },
            "properties": [
                {"name": "dekopon:deterministic", "value": "true"},
                {"name": "dekopon:target", "value": TARGET},
            ],
        },
        "components": components,
        "dependencies": dependencies,
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def check_or_write(path: Path, expected: str, write: bool) -> bool:
    if write:
        path.write_text(expected, encoding="utf-8", newline="\n")
        return True
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    print(f"error: generated content is stale: {path.relative_to(ROOT)}", file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-tracked", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--format", choices=("text", "json", "cyclonedx"))
    parser.add_argument("--output", type=Path)
    arguments = parser.parse_args()
    if arguments.format and not arguments.output:
        parser.error("--format requires --output")
    if arguments.output and not arguments.format:
        parser.error("--output requires --format")
    if not (arguments.write_tracked or arguments.check or arguments.format):
        parser.error("choose --write-tracked, --check, or --format with --output")

    metadata = cargo_metadata()
    inventory, edges, root_id = closure(metadata)
    verify_against_cargo_tree(metadata, inventory, root_id)
    success = True
    if arguments.write_tracked or arguments.check:
        inventory_path = ROOT / "security" / "wasm-dependencies.txt"
        notices_path = ROOT / "THIRD_PARTY_NOTICES.md"
        existing_notices = notices_path.read_text(encoding="utf-8")
        expected_notices = replace_notices(existing_notices, notices_block(inventory))
        success &= check_or_write(inventory_path, text_inventory(inventory), arguments.write_tracked)
        success &= check_or_write(notices_path, expected_notices, arguments.write_tracked)
    if arguments.format:
        if arguments.format == "text":
            rendered = text_inventory(inventory)
        elif arguments.format == "json":
            rendered = json_inventory(inventory)
        else:
            rendered = cyclonedx(metadata, inventory, edges, root_id)
        output = arguments.output
        assert output is not None
        if not output.is_absolute():
            output = ROOT / output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0 if success else 1


if __name__ == "__main__":
    raise SystemExit(main())
